FROM python:3.10.14-bookworm

# Install MySQL client
RUN apt-get update && \
    apt-get install -y mysql-client


WORKDIR /crocosoft-task

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
